docs(readme): updated README based on new setup
Greenstand/treetracker-wallet-api pull request #373
Opened 2023-07-05 15:48 UTC by joonaun93

Updated the README based on my own setup.

2023-07-05 16:46 UTC, sebastiangaertner commented
@Kpoke could you check this please and merge if correct. For example the non ssl get parameter is for anyone the same or might there be differences depending on your environment and settings?

2023-07-05 23:34 UTC, Kpoke requested changes

2023-07-05 23:34 UTC, Kpoke commented on README.md
> +const privateKEY = process.env.PRIVATE_KEY.replace(/\\n/g, '\n');
You can replace this in the file itself,  so there won't be a need for this

2023-07-05 23:34 UTC, Kpoke commented on README.md
> +1. To set up a local server with some seed data, temporarily copy the following (from serverTest.js) and paste into server/server.js:
can you add a new script and remove the serverTest.js file altogether? So to set up a local server with some seed data would still be npm run server-test but the server-test script would be `npm run test-seed and npm run server`

2023-07-05 23:34 UTC, Kpoke commented on README.md
> +DATABASE_URL=postgresql://wallet_user:secret@localhost:5432/wallet_user
Can you make it `?false` or put it as an option?  Also, can you add a disclaimer that ssl=no-verify should be used if the database is not locally hosted

2023-07-08 07:29 UTC, joonaun93 commented
Hi @Kpoke, made the changes according to the comments.

2023-07-10 15:24 UTC, Kpoke commented on README.md
> +DATABASE_URL=postgresql://wallet_user:secret@localhost:5432/wallet_user?ssl=false
it is actually ?false not ?ssl=false

2023-07-10 15:37 UTC, merged